variables:
  deploy_host: martynbristow.co.uk

build:
  image: jpbernius/xelatex 
  script:
    - xelatex main.tex
  artifacts:
    paths:
      - main.pdf

deploy:
  stage: deploy
  script:
    # install ssh-agent
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    # run ssh-agent
    - eval $(ssh-agent -s)
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - rsync -avz _build/* martyn@martyn.martynbristow.co.uk:/var/www/html/martynbristow/static/martyn-bristow.co.uk
  environment:
    name: martyn
    url: http://martynbristow.co.uk/static/martyn-bristow.pdf
  only:
    - master